services:
  - type: web
    name: ecoexchange-api
    env: python
    buildCommand: "pip install -r requirements.txt ; python data/generate_data.py ; python analyze_datasets.py ; python models/train_forecaster.py ; python models/train_suggester.py"
    startCommand: "uvicorn api.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PORT
        value: 10000
